/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/oJKF4gkXCyI
 */
import { AvatarImage, AvatarFallback, Avatar } from "#components/ui/avatar.tsx";
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  Card,
} from "#components/ui/card.tsx";
import { channels } from "#db/schema.ts";
import { db } from "#db/index.ts";
import Link from "next/link";
import { channelNameToUrlSafe } from "#lib/utils.ts";

export async function ChannelList() {
  const channelList = await db.select().from(channels).orderBy(channels.name);
  return (
    <div className="grid sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-6">
      {channelList.map((channel) => {
        return (
          <Link key={channel.id} href={channel.slug}>
            <Card>
              <CardHeader className="p-4">
                <div className="flex items-center space-x-4">
                  <Avatar className="w-12 h-12">
                    <AvatarImage alt="User avatar" src={channel.avatar} />
                    <AvatarFallback>
                      {channel.name[0].toLocaleUpperCase()}
                    </AvatarFallback>
                  </Avatar>
                  <div className="space-y-1.5">
                    <CardTitle className="text-base">{channel.name}</CardTitle>
                    <CardDescription className="text-sm">
                      {channel.xHandle}
                    </CardDescription>
                  </div>
                </div>
              </CardHeader>
              <CardContent className="p-4">
                <p className="text-sm">{channel.description}</p>
              </CardContent>
            </Card>
          </Link>
        );
      })}
    </div>
  );
}
