/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/CVuDGOz8NTJ
 */
import { LeftNav } from "./left-nav";
import { Chat } from "./chat";
import { Main } from "./main";

export function Starter() {
  return (
    <div className="flex h-screen bg-[#0e0e10]">
      {/* Background dimmer! */}
      {/* <div className="absolute z-10 bg-black/35 h-screen w-screen"></div> */}
      <LeftNav />
      <Main />
      <Chat />
    </div>
  );
}
