/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/CVuDGOz8NTJ
 */
import { LeftNav } from "./left-nav";
import { Chat } from "./chat";
import { Main } from "./main";

export function Starter() {
  return (
  );
}
